apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-master
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      serviceAccountName: jenkins
      containers:
       - name: jenkins-leader
         image: phanikumary1995/jenkins-oracle-jdk8
         #image: jenkins/jenkins:lts
         volumeMounts:
          - name: persistent-storage
            mountPath: /var/jenkins_home
          - name: docker-sock-volume
            mountPath: /var/run/docker.sock
         resources:
           requests:
             memory: "2048Mi"
             cpu: "0.5"
           limits:
             memory: "2048Mi"
             cpu: "1.0"
         ports:
           - name: http-port
             containerPort: 8080
           - name: jnlp-port
             containerPort: 50000
         readinessProbe:
             tcpSocket:
               port: 80
             initialDelaySeconds: 30
             timeoutSeconds: 1
             periodSeconds: 5
             successThreshold: 1
         livenessProbe:
             tcpSocket:
               port: 80
             initialDelaySeconds: 30
             timeoutSeconds: 1
             periodSeconds: 2
             failureThreshold: 3
      volumes:
       - name: docker-sock-volume
         hostPath:
           path: /var/run/docker.sock
       - name: persistent-storage
         persistentVolumeClaim:
           claimName: jenkins-pv-claim

    #  nodeSelector:
     #   server: node2
